#!/bin/bash


rofi_command="rofi -theme $HOME/.config/polybar/scripts/themes/powermenu_alt.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
shutdown="󰐥 Apagar"
reboot="󰑓 Reiniciar"
lock=" Bloquear"
suspend=" Suspender"
logout="󰍃 Salir"

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "Sistema" -dmenu -selected-row 0)"
case $chosen in
    $shutdown)
        poweroff
        ;;
    $reboot)
        reboot
        ;;
    $lock)
        bash ~/.config/polybar/scripts/lock
        ;;
    $suspend)
        mpc -q pause
        amixer set Master mute
        bash ~/.config/polybar/scripts/suspend.sh
        ;;
    $logout)
        openbox --exit
        ;;
esac
